# \u03a1\u03c5\u03b8\u03bc\u03af\u03c3\u03b5\u03b9\u03c2 \u0392\u03ac\u03c3\u03b7\u03c2 \u0394\u03b5\u03b4\u03bf\u03bc\u03ad\u03bd\u03c9\u03bd
spring.datasource.url=jdbc:mysql://localhost:3306/support_system?createDatabaseIfNotExist=true
spring.datasource.username=root
# \u0391\u03bd \u03ad\u03c7\u03b5\u03b9\u03c2 \u03ba\u03c9\u03b4\u03b9\u03ba\u03cc \u03c3\u03c4\u03b7 MySQL, \u03b3\u03c1\u03ac\u03c8\u03c4\u03bf\u03bd \u03bc\u03b5\u03c4\u03ac \u03c4\u03bf =, \u03b1\u03bb\u03bb\u03b9\u03ce\u03c2 \u03ac\u03c6\u03b7\u03c3\u03ad \u03c4\u03bf \u03ba\u03b5\u03bd\u03cc
spring.datasource.password=

spring.security.user.name=admin
spring.security.user.password=1234

# JPA / Hibernate \u03a1\u03c5\u03b8\u03bc\u03af\u03c3\u03b5\u03b9\u03c2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port \u03b5\u03c6\u03b1\u03c1\u03bc\u03bf\u03b3\u03ae\u03c2
server.port=8080

# Mail / Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0c78c090be431f
spring.mail.password=48792edca71392
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true